#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["graphql-example/graphql-example.csproj", "graphql-example/"]
RUN dotnet restore "graphql-example/graphql-example.csproj"
COPY . .
WORKDIR "/src/graphql-example"
RUN dotnet build "graphql-example.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "graphql-example.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "graphql-example.dll"]